### ISSUE TITLE
Bug: The "New" button does not work

### ISSUE THREAD

**Issue by davidmyersdev** [davidmyersdev/octo#299]
## Summary

After starting a conversation with the Assistant, the "New" button does not work. You have to navigate to another page (such as the history page) and then click "New" from there.

### Steps to reproduce

- Navigate to `/assistant`
- Start a conversation (requires an OpenAI API token)
- Click "New"
- Nothing happens

**Comment by 3thanHead** [comment]
would this one have conflicts? low hanging fruit.

**Comment by davidmyersdev** [comment]
@3thanHead this one should be safe to pick up!

**Comment by 3thanHead** [comment]
@davidmyersdev technically, since this view is used to create a new conversation, wouldn't there be no need for a "New" button here, since it would only redirect to the same page. All it currently does is increment the query string:
https://github.com/davidmyersdev/octo/blob/main/components/AssistantContainer.vue#L12
https://github.com/davidmyersdev/octo/blob/main/composables/useSoftNavigation.ts#L8

**Comment by 3thanHead** [comment]
Understood. Played around with this a bit. If I remove this watcher (https://github.com/davidmyersdev/octo/blob/main/components/AssistantContainer.vue#L14-L20) and add redirect with vue router instead when message is submitted, bug is solved. Putting PR up for this.

**Comment by davidmyersdev** [comment]
Fixed in #302! Thanks so much @3thanHead! 🎉
